AllCops:
  TargetRubyVersion: 2.3

  # Include gemspec and Rakefile
  Include:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
  Exclude:
    - 'vendor/**/*'
    - 'stubs/**/*'
    - 'spec/support/shared_contexts/*'

# Checks formatting of special comments
CommentAnnotation:
  Keywords:
    - TODO
    - FIXME
    - OPTIMIZE
    - HACK
    - REVIEW

########################################
# Style Cops

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/RegexpLiteral:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

########################################
# Lint Cops

Lint/Eval:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

########################################
# Metrics Cops

Metrics/LineLength:
  Max: 110

Metrics/MethodLength:
  CountComments: false # count full line comments?
  Max: 30

Metrics/ClassLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

# rubocop:disable Metrics/AbcSize
# rubocop:disable Metrics/MethodLength
# rubocop:disable Metrics/BlockLength
